import numpy as np

class Step:
    """Representation of a particle's single tracking step."""
    def __init__(self, parent_track, data_dict):
        self.step_id = data_dict['StepID']
        self.start_pos = np.array(
            [data_dict['StartX'], data_dict['StartY'], data_dict['StartZ']])
        self.end_pos = np.array(
            [data_dict['EndX'], data_dict['EndY'], data_dict['EndZ']])
        self.start_time = data_dict['StartTime']
        self.end_time = data_dict['EndTime']
        self.velocity = data_dict['Velocity']
        self.energy = data_dict['Energy']
        self.parent_track = parent_track
        self.child_tracks = []

class Track:
    """Representation of a particle's trajectory made of sequential Steps."""
    def __init__(self, parent_event, data_dict):
        self.track_id = data_dict["TrackID"]

        self.particle_type = data_dict.get("ParticleType", None)
        self.creator_process = data_dict.get("CreatorProcess", None)
        self.destroying_process = None
        self._parent_track_ref = {
            "parent_track_id": data_dict.get("ParentTrackID", None),
            "parent_step_id": data_dict.get("ParentStepID", None),
            }

        self.parent_event = parent_event
        self.child_tracks = []
        self.steps_dict = {}

    @property
    def steps(self):
        return sorted(self.steps_dict.values(), key=lambda s: s.step_id)

    @property
    def points(self):
        steps = self.steps
        return np.array([s.start_pos for s in steps]+[steps[-1].end_pos])

    def _validate(self):
        steps = self.steps
        for i in range(len(steps)-1):
            if not np.allclose(steps[i].end_pos, steps[i+1].start_pos):
                raise ValueError(f"unequal start/end points of subsequent "
                    f"steps {steps[i].end_pos} & {steps[i+1].start_pos}")
            if steps[i].end_time != steps[i+1].start_time:
                raise ValueError(f"unequal start/end times of subsequent "
                    f"steps {steps[i].time} & {steps[i+1].time}")

    def _check_compatibility(self, data_dict):
        if self.particle_type != data_dict.get("ParticleType", None):
            raise ValueError("incompatible ParticleType")
        if self.creator_process != data_dict.get("CreatorProcess", None):
            raise ValueError("incompatible CreatorProcess")
        if self._parent_track_ref["parent_track_id"] != data_dict.get(
                "ParentTrackID", None):
            raise ValueError("incompatible ParentTrackID")
        if self._parent_track_ref["parent_step_id"] != data_dict.get(
                "ParentStepID", None):
            raise ValueError("incompatible ParentStepID")

    def info_str(self, indent=0):
        s = " "*(4*indent)
        s += self.particle_type
        s += f" ({'primary' if self.parent_track is None
            else 'generated by '+self.creator_process})"
        s += f" (destroyed by {self.destroying_process})\n"
        for child in self.child_tracks:
            s += child.info_str(indent=indent+1)
        return s

class Event:
    """Representation of a full simulation event containing multiple Tracks."""
    def __init__(self, data_dict):
        self.event_id = data_dict["EventID"]
        self.tracks_dict = {}

    @property
    def tracks(self):
        return sorted(self.tracks_dict.values(), key=lambda t: t.track_id)

    @property
    def primary_track(self):
        lst = [t for t in self.tracks if t.parent_track is None]
        if len(lst) != 1:
            raise ValueError(f"failed to find exactly 1 orphan track in "
                f"event (instead found {len(lst)})")
        return lst[0]

    def info_str(self):
        return self.primary_track.info_str()

def read_tracking_info(root):
    """Parses an AIDA XML root element into an object-oriented structure.

    Parameters
    ----------
    root: xml.etree.ElementTree.Element

    Returns
    -------
    List[Event]: A list of Event objects.
    """
    tuple_element = root.find(".//tuple")
    if tuple_element is None:
        tuple_element = root if root.tag == 'tuple' else None

    if tuple_element is None:
        print("Warning: No <tuple> element found in the XML tree.")
        return []

    # 1. Read column descriptors
    columns_info = []
    for col in tuple_element.findall(".//column"):
        name = col.attrib['name']
        col_type = col.attrib.get('type', 'double')
        columns_info.append((name, col_type))
    if not columns_info:
        raise ValueError(f"malformed xml structure with no column descriptors")

    # 2. Read rows; extract typed ntuples
    rows_section = tuple_element.find("rows")
    if rows_section is None:
        return []
    ntuples = []
    for row_node in rows_section.findall("row"):
        entries = row_node.findall("entry")
        if len(entries) != len(columns_info):
            raise ValueError(f"malformed row with {len(entries)} entries "
                f"(expected {len(columns_info)})")
        raw_dict = {}
        for (col_name, col_type), entry_node in zip(columns_info, entries):
            val = entry_node.attrib.get('value', '')
            raw_dict[col_name] = int(val) if col_type == 'int' else (float(val) if col_type == 'double' else val)
        ntuples.append(raw_dict)


    event_dict = {}
    for ntuple in ntuples:
        event_id = ntuple["EventID"]
        track_id = ntuple["TrackID"]
        step_id = ntuple["StepID"]

        if not event_id in event_dict:
            event_dict[event_id] = Event(ntuple)
        event = event_dict[event_id]

        if not track_id in event.tracks_dict:
            event.tracks_dict[track_id] = Track(event, ntuple)
        track = event.tracks_dict[track_id]
        track._check_compatibility(ntuple)

        if not step_id in track.steps_dict:
            track.steps_dict[step_id] = Step(track, ntuple)
        step = track.steps_dict[step_id]

        if ntuple["DestroyingProcess"] != "None":
            if track.destroying_process is not None:
                raise ValueError("trying to assing DestroyingProcess but "
                    "track already has one")
            track.destroying_process = ntuple["DestroyingProcess"]

    # link track parent relationship
    for event in event_dict.values():
        for track in event.tracks_dict.values():
            track._validate()
            parent_track_id = track._parent_track_ref["parent_track_id"]
            parent_step_id = track._parent_track_ref["parent_step_id"]
            parent_track = event.tracks_dict.get(parent_track_id, None)
            if parent_track:
                parent_step = parent_track.steps_dict.get(parent_step_id, None)
            else:
                parent_step = None
            track.parent_track = parent_track
            if parent_track:
                parent_track.child_tracks.append(track)
            track.parent_step = parent_step
            if parent_step:
                parent_step.child_tracks.append(track)
            del track._parent_track_ref

    event_list = sorted(event_dict.values(), key=lambda e: e.event_id)
    return event_list
