from typing import List
import numpy as np

class Step:
    """Representation of a particle's single tracking step."""
    def __init__(self, parent_track, data_dict):
        self.step_id = data_dict['StepID']
        self.start_pos = np.array(
            [data_dict['StartX'], data_dict['StartY'], data_dict['StartZ']])
        self.end_pos = np.array(
            [data_dict['EndX'], data_dict['EndY'], data_dict['EndZ']])
        self.start_time = data_dict['StartTime']
        self.end_time = data_dict['EndTime']
        self.velocity = data_dict['Velocity']
        self.energy = data_dict['Energy']
        self.parent_track = parent_track
        self.child_tracks = []

    @property
    def is_last(self):
        return (self is self.parent_track.steps[-1])

class Track:
    """Representation of a particle's trajectory made of sequential Steps."""
    def __init__(self, parent_event, data_dict):
        self.track_id = data_dict["TrackID"]

        self.particle_type = data_dict.get("ParticleType", None)
        self.creator_process = data_dict.get("CreatorProcess", None)
        self.destroying_process = None
        self._parent_track_ref = {
            "parent_track_id": data_dict.get("ParentTrackID", None),
            "parent_step_id": data_dict.get("ParentStepID", None),
            }

        self.parent_event = parent_event
        self.child_tracks = []
        self.steps_dict = {}

    @property
    def steps(self):
        return sorted(self.steps_dict.values(), key=lambda s: s.step_id)

    @property
    def start_time(self):
        return self.steps[0].start_time

    @property
    def end_time(self):
        return self.steps[-1].end_time

    @property
    def start_pos(self):
        return self.steps[0].start_pos

    @property
    def end_pos(self):
        return self.steps[-1].end_pos

    @property
    def points(self):
        steps = self.steps
        return np.array([s.start_pos for s in steps]+[steps[-1].end_pos])

    def _validate(self):
        steps = self.steps
        for i in range(len(steps)-1):
            if not np.allclose(steps[i].end_pos, steps[i+1].start_pos):
                raise ValueError(f"unequal start/end points of subsequent "
                    f"steps {steps[i].end_pos} & {steps[i+1].start_pos}")
            if steps[i].end_time != steps[i+1].start_time:
                raise ValueError(f"unequal start/end times of subsequent "
                    f"steps {steps[i].time} & {steps[i+1].time}")

    def _check_compatibility(self, data_dict):
        if self.particle_type != data_dict.get("ParticleType", None):
            raise ValueError("incompatible ParticleType")
        if self.creator_process != data_dict.get("CreatorProcess", None):
            raise ValueError("incompatible CreatorProcess")
        if self._parent_track_ref["parent_track_id"] != data_dict.get(
                "ParentTrackID", None):
            raise ValueError("incompatible ParentTrackID")
        if self._parent_track_ref["parent_step_id"] != data_dict.get(
                "ParentStepID", None):
            raise ValueError("incompatible ParentStepID")

    def info_str(self, indent_prefix=""):
        s = indent_prefix + self.particle_type
        s += f" ({'primary' if self.parent_track is None
            else 'generated by '+self.creator_process})"
        s += f" (destroyed by {self.destroying_process})\n"
        ctrks = self.child_tracks
        for i, child in enumerate(ctrks):
            s += child.info_str(indent_prefix="    "+indent_prefix)
        return s

    def info_str(self, prefix="", is_tail=True, is_root=True):

        content = self.particle_type
        content += f" ({'primary' if self.parent_track is None
            else 'generated by '+self.creator_process})"
        content += f" (destroyed by {self.destroying_process})"

        if is_root:
            result = f"{content}\n"
            new_prefix = ""
        else:
            connector = "└── " if is_tail else "├── "
            result = f"{prefix}{connector}{content}\n"
            new_prefix = prefix + ("    " if is_tail else "│   ")

        # Recursively process all children
        chtrks = sorted(self.child_tracks, key=lambda t: t.steps[0].start_time)
        for i, child in enumerate(chtrks):
            result += child.info_str(
                prefix=new_prefix,
                is_tail=(i==len(chtrks)-1),
                is_root=False,)

        return result

class Event:
    """Representation of a full simulation event containing multiple Tracks."""
    def __init__(self, data_dict):
        self.event_id = data_dict["EventID"]
        self.tracks_dict = {}

    def parse_interactions(self):
        interaction_dict = {}
        for track in self.tracks:
            if track.parent_track is None:
                continue
            if not track.parent_step in interaction_dict:
                interaction_dict[track.parent_step] = []
            interaction_dict[track.parent_step].append(track)

        self.interactions = []
        for primary_step, secondary_tracks in interaction_dict.items():
            self.interactions.append(
                Interaction(primary_step, secondary_tracks))

        for track in self.tracks:
            last_step = track.steps[-1]
            if not last_step in interaction_dict and track.destroying_process != "Transportation":
                self.interactions.append(Interaction(last_step, []))

    @property
    def tracks(self):
        return sorted(self.tracks_dict.values(), key=lambda t: t.track_id)

    @property
    def primary_track(self):
        lst = [t for t in self.tracks if t.parent_track is None]
        if len(lst) != 1:
            raise ValueError(f"failed to find exactly 1 orphan track in "
                f"event (instead found {len(lst)})")
        return lst[0]

    def info_str(self):
        return self.primary_track.info_str()

def read_tracking_info(root):
    """Parses an AIDA XML root element into an object-oriented structure.

    Parameters
    ----------
    root: xml.etree.ElementTree.Element

    Returns
    -------
    List[Event]: A list of Event objects.
    """
    tuple_element = root.find(".//tuple")
    if tuple_element is None:
        tuple_element = root if root.tag == 'tuple' else None

    if tuple_element is None:
        print("Warning: No <tuple> element found in the XML tree.")
        return []

    # 1. Read column descriptors
    columns_info = []
    for col in tuple_element.findall(".//column"):
        name = col.attrib['name']
        col_type = col.attrib.get('type', 'double')
        columns_info.append((name, col_type))
    if not columns_info:
        raise ValueError(f"malformed xml structure with no column descriptors")

    # 2. Read rows; extract typed ntuples
    rows_section = tuple_element.find("rows")
    if rows_section is None:
        return []
    ntuples = []
    for row_node in rows_section.findall("row"):
        entries = row_node.findall("entry")
        if len(entries) != len(columns_info):
            raise ValueError(f"malformed row with {len(entries)} entries "
                f"(expected {len(columns_info)})")
        raw_dict = {}
        for (col_name, col_type), entry_node in zip(columns_info, entries):
            val = entry_node.attrib.get('value', '')
            raw_dict[col_name] = int(val) if col_type == 'int' else (float(val) if col_type == 'double' else val)
        ntuples.append(raw_dict)


    event_dict = {}
    for ntuple in ntuples:
        event_id = ntuple["EventID"]
        track_id = ntuple["TrackID"]
        step_id = ntuple["StepID"]

        if not event_id in event_dict:
            event_dict[event_id] = Event(ntuple)
        event = event_dict[event_id]

        if not track_id in event.tracks_dict:
            event.tracks_dict[track_id] = Track(event, ntuple)
        track = event.tracks_dict[track_id]
        track._check_compatibility(ntuple)

        if not step_id in track.steps_dict:
            track.steps_dict[step_id] = Step(track, ntuple)
        step = track.steps_dict[step_id]

        if ntuple["DestroyingProcess"] != "None":
            if track.destroying_process is not None:
                raise ValueError("trying to assing DestroyingProcess but "
                    "track already has one")
            track.destroying_process = ntuple["DestroyingProcess"]

    # link track parent relationship
    for event in event_dict.values():
        for track in event.tracks_dict.values():
            track._validate()
            parent_track_id = track._parent_track_ref["parent_track_id"]
            parent_step_id = track._parent_track_ref["parent_step_id"]
            parent_track = event.tracks_dict.get(parent_track_id, None)
            if parent_track:
                parent_step = parent_track.steps_dict.get(parent_step_id, None)
            else:
                parent_step = None
            track.parent_track = parent_track
            if parent_track:
                parent_track.child_tracks.append(track)
            track.parent_step = parent_step
            if parent_step:
                parent_step.child_tracks.append(track)
            del track._parent_track_ref

    event_list = sorted(event_dict.values(), key=lambda e: e.event_id)
    for event in event_list:
        event.parse_interactions()
    return event_list

class Interaction:
    def __init__(self, primary_step: Step, secondary_tracks: List[Track]):
        self.primary_step = primary_step
        self.primary_track = primary_step.parent_track

        if secondary_tracks:
            self.interaction_process = secondary_tracks[0].creator_process
        else:
            self.interaction_process = self.primary_track.destroying_process
        if any((t.creator_process != self.interaction_process) for t in secondary_tracks):
            raise ValueError(f"Incompatible creator processes of interaction "
                f"secondaries: {[t.creator_process for t in secondary_tracks]}")

        self.position = primary_step.end_pos
        self.time = primary_step.end_time
        self.secondary_tracks = secondary_tracks
        self.is_primary_destroyed = primary_step.is_last

    def __str__(self):
        prim = self.primary_track.particle_type
        sec = sorted([t.particle_type for t in self.secondary_tracks])
        return f"INTERACTION {self.interaction_process}: {prim} -> " \
            f"{'' if self.is_primary_destroyed else prim+' (scattered) + '} " \
            f"{' + '.join(sec)}"
